name: musik
description: A new Flutter project for UAS Musik ML.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0" # Ini constraint yang disarankan (lower-bound ^3.4.0, upper <4.0.0)
  flutter: ">=3.22.0" # Sesuaikan dengan versi Flutter-mu

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1 # Untuk play musik
  ml_linalg: ^13.12.6 # Untuk ML (vektor & KNN sederhana)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
